name: Daily Option Screener

on:
  # Schedule: # Runs at 18:00 UTC (10:00 AM PST / 11:00 AM PDT)
  # Note: GitHub servers use UTC time.
  schedule:
    - cron: '0 18 * * 1-5' # Runs Mon-Fri only
  
  # Manual Trigger: Allows you to click a "Run Now" button in GitHub UI
  workflow_dispatch:

jobs:
  run-screener:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      
      - name: Set up Python
        run: uv python install 3.13

      - name: Install Dependencies
        run: uv sync --frozen

      - name: Create config.py from Secret
        env:
          CONFIG_DATA: ${{ secrets.CONFIG_FILE_BASE64 }}
        run: |
          echo "$CONFIG_DATA" | base64 --decode > shared/config.py

      - name: Run Main Script
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_CREDENTIALS_BASE64 }}
        run: uv run screener/main.py
